spring:
  application:
    name: zuul-sare
  thymeleaf:
    cache: false

zuul:
  routes:
    external:
      url: http://placekitten.com
    internal:
      url: ${INTERNAL_APP_URL:http://localhost:9999}