security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://cso.login.run.pivotal.io/token_keys
    client:
      accessTokenUri: https://cso.login.run.pivotal.io/oauth/token
      userAuthorizationUri: https://cso.login.run.pivotal.io/oauth/authorize
      clientId: bde1358e-6cf8-4fbd-91a5-fc1a1e2fc59d
      clientSecret: 2665905b-65fe-488d-a628-48a27f9618be

ssoServiceUrl: https://cso.login.run.pivotal.io

pivotal:
  resource:
    jwk:
      key-set-uri: https://cso.login.run.pivotal.io/token_keys
  client:
    accessTokenUri: https://cso.login.run.pivotal.io/oauth/token
    userAuthorizationUri: https://cso.login.run.pivotal.io/oauth/authorize
    clientId: bde1358e-6cf8-4fbd-91a5-fc1a1e2fc59d
    clientSecret: 2665905b-65fe-488d-a628-48a27f9618be
    clientAuthenticationScheme: form
facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG
