spring:
  application:
    name: auth-sare

server:
  port: 5555

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

---
spring:
  profiles: local

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://cso.login.run.pivotal.io/token_keys
    client:
      accessTokenUri: https://cso.login.run.pivotal.io/oauth/token
      userAuthorizationUri: https://cso.login.run.pivotal.io/oauth/authorize
      clientId: bde1358e-6cf8-4fbd-91a5-fc1a1e2fc59d
      clientSecret: 2665905b-65fe-488d-a628-48a27f9618be

ssoServiceUrl: https://cso.login.run.pivotal.io